name: Build Docker Image and Push to GitHub Packages

on:
  push:
    branches:
      - main  # 只在主分支推送时触发构建，可以根据需要更改

jobs:
  build:
    runs-on: ubuntu-latest  # 使用Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU (only for ARM builds, if needed)
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Build Docker image
      run: |
        docker build -t your-image-name:latest .

    - name: Authenticate with GitHub Packages
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

    - name: Tag Docker image
      run: docker tag your-image-name:latest docker.pkg.github.com/${{ github.repository }}/your-image-name:latest

    - name: Push Docker image to GitHub Packages
      run: docker push docker.pkg.github.com/${{ github.repository }}/your-image-name:latest
