name: Build Docker arm64 Image

on:
  push:
    branches:
      - main  # 只在主分支推送时触发构建，可以根据需要更改

jobs:
  build:
    runs-on: ubuntu-latest  # 使用Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Build Docker image
      run: docker build -t your-image-name:latest -f Dockerfile .

    - name: Save Docker image to archive
      run: |
        mkdir -p artifacts
        docker save -o artifacts/image.tar your-image-name:latest

    - name: Upload Docker image to GitHub Package Registry
      uses: docker/upload-action@v2
      with:
        name: latest
        registry: ghcr.io
        image: your-image-name
        path: artifacts/image.tar
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
